add: добавить сущность Режиссер и функциональность для работы с ней
AlexOdnoshivkin/java-filmorate pull request #11
Opened 2022-08-17 12:40 UTC by MaksimOrekhoff

2022-08-17 13:46 UTC, PolinaMalakovich requested changes
Посмотрела пул реквест, оставила два комментария.

2022-08-17 13:46 UTC, PolinaMalakovich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Film> films = getAll();
Запрашивать все записи таблицы и делать сортировку и фильтрацию на стороне java не оптимально. Оптимально и по памяти, и по времени сделать это на уровне sql. Для этого в зависимости от переданного `sordBy` в сторадже выбирать нужный sql реквест. Вот пример сортировки фильмов по количеству лайков: [DbFilmStorage.java#L77-L87](https://github.com/PolinaMalakovich/java-filmorate/blob/c70fbd21ecfed347c41218587c096c5e51c822c8/src/main/java/ru/yandex/practicum/filmorate/storage/film/DbFilmStorage.java#L77-L87)

2022-08-17 13:46 UTC, PolinaMalakovich commented on src/main/java/ru/yandex/practicum/filmorate/model/users/User.java
> +public class User  implements IdControllable {
Кажется, что изменения в этом файле случайны, потому что добавляются только пробелы и перемещаются импорты. Стоит избегать изменений, которые не оносятся к задаче. В крайнем случае, выносить их в отдельный комит. Мы команда на две недели, за это время мы не успеем выработать единый командный стиль, поэтому лучше следовать стилю уже написанного.

Откатить случайные изменения в одном файле целиком поможет эта команда: 
```bash
git checkout COMMIT_ID -- path/to/file
```
Где:
-  `COMMIT_ID` - это хэш комита, к которому хочется вернуть файл;
-  `path/to/file` - это путь к файлу, который откатываем

**UPD**: Заметила также в других файлах подобные изменения.

2022-08-19 13:15 UTC, PolinaMalakovich approved these changes
Как обсудили с @MaksimOrekhoff в слаке, ребезнула ветку, поправила историю.

2022-08-19 13:18 UTC, AlexOdnoshivkin commented
Хорошо. В плане коммитов если что не страшно, я при мёрдже всё в 1 сливаю

2022-08-19 13:18 UTC, PolinaMalakovich commented
Чтобы избежать подобных проблем в будещем, было бы здорово пройти [Learn Branching](https://learngitbranching.js.org)

2022-08-19 13:19 UTC, MaksimOrekhoff commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Film> films = getAll();
сортировка и поиск в классе FilmDbStorage

2022-08-19 13:20 UTC, MaksimOrekhoff commented
> Чтобы избежать проблем в будещем, было бы здорово пройти [Узнать Ветвление](https://learngitbranching.js.org)

сохранил

2022-08-19 13:21 UTC, PolinaMalakovich commented
> Хорошо. В плане коммитов если что не страшно, я при мёрдже всё в 1 сливаю

Тут вместо ребейза был черипик, ветка росла не из того состояния и дублировала модифицированное состояние из других веток. В итоге изменялись все файлы в проекте.

2022-08-19 14:33 UTC, AlexOdnoshivkin approved these changes

2022-08-19 18:18 UTC, merged