feat: add-search
AlexOdnoshivkin/java-filmorate pull request #18
Opened 2022-08-20 20:58 UTC by AlexOdnoshivkin

2022-08-21 10:24 UTC, MaksimOrekhoff approved these changes

2022-08-21 10:24 UTC, MaksimOrekhoff commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +                "FROM films AS f " +
здесь видимо применилось автоматическое форматирование кода Ctrl + Alt + L. изменились отступы

2022-08-21 10:32 UTC, PolinaMalakovich requested changes

2022-08-21 10:32 UTC, PolinaMalakovich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Film> searchByName = new ArrayList<>();
Я бы сделала иначе:
- вместо листов создать пустые стримы 
- в ифах не коллектить стрим
- присоединять директоров и жанры не в ифах, а один раз после объединения стримов

```java
Stream<Film> byDirector = by.contains("director") ? storage.searchFilmByDirector(query) : Stream.empty();
Stream<Film> byName = by.contains("title") ? storage.searchFilmByName(query) : Stream.empty();

Stream.concat(byDirector, byName)
  .distinct()
  .peek(directorDBStorage::setFilmDirector)
  .peek(genreStorage::setFilmGenre)
  .sorted(Comparator.comparingInt(film -> film.getLikes().size()));
```

2022-08-21 10:32 UTC, PolinaMalakovich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .sorted(Comparator.comparingInt(film -> film.getLikes().size()));
Выборку и сортировку можно сделать на стороне sql, если написать три отдельных запроса: 
- `searchFilmByName(String query, String name)`
- `searchFilmByDirector(String query, String director)`
- `searchFilmByNameAndDirector(String query, String name, String director)`

Я в своей задаче так сделала: [FilmDbStorage.java#L122-L209](https://github.com/AlexOdnoshivkin/java-filmorate/blob/39af17dfb60faa0ddc136f52657275bae56aa39b/src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java#L122-L209). Сортировать на стороне sql всегда дешевле.

2022-08-21 10:37 UTC, PolinaMalakovich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Film> searchByName = new ArrayList<>();
На `collect` уходит время и память, поэтому лучше лишний раз его не делать

2022-08-21 11:47 UTC, AlexOdnoshivkin commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        String filter = "HAVING f.NAME ILIKE " + "'%" + query + "%'";
Отрабатывал запросы через консоль, перед тем как писать в код, работает только с HAVING. Есть вариант сделать по-другому, сделать отбор в INNER JOIN, вот так. Но тут проблема как раз в переменной фильтр. Я изначально так и хотел сделать, как ты говоришь, просто внедрять переменную, но java не хочет воспринимать её в таком формате (т.е. я писал ILIKE ? в запросе). Пробовал по-разному настраивать, но не получилось, пол вечера вчера на это убил. Получилось вот так, сложением строк.
![image](https://user-images.githubusercontent.com/100222349/185789290-3a3d3f20-4576-49cf-bf08-eb02c4bda9a9.png)

2022-08-21 12:44 UTC, AlexOdnoshivkin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .sorted(Comparator.comparingInt(film -> film.getLikes().size()));
Сортировку сделал так, потому-что мне показалась такая реализация проще. Воспользоваться готовыми методами я не могу, потому-что на момент сортировки у меня уже есть готовая выборка фильмов. Можно было бы сделать сортировку прямо в запросе, но у меня их объединяется несколько в зависимости от условий.

2022-08-21 12:49 UTC, AlexOdnoshivkin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Film> searchByName = new ArrayList<>();
Да, такой вариант куда красивее получается, спасибо)

2022-08-21 15:41 UTC, PolinaMalakovich commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        String filter = "HAVING f.NAME ILIKE " + "'%" + query + "%'";
Попробовала с `WHERE`, у меня вот такой запрос прошел в консоли и вернул нужный фильм:
```sql
SELECT f.film_id,
       f.name,
       f.description,
       f.release_date,
       f.duration,
       f.mpa_id,
       m.name
FROM films AS f
INNER JOIN mpa AS m ON m.mpa_id = f.mpa_id
INNER JOIN films_directors AS fd ON f.film_id = fd.film_id
INNER JOIN directors AS D ON fd.director_id = d.director_id
WHERE director_name ILIKE '%upDatE%'
GROUP BY f.film_id;
```
Если ты хочешь экранировать `query` перед вставкой в запрос, то можно строчку `WHERE` поменять на такую:
```sql
WHERE director_name ILIKE ?
```
И в `jdbcTemplate` потом передавать параметр вот так:
```java
jdbcTemplate.query(sqlQuery, aMapper, "%" + query + "%");
```
Ошибка, с которой ты столкнулся, думаю, могла быть потому что в твоем запросе `WHERE`  шел после `GROUP BY`.

2022-08-21 15:48 UTC, PolinaMalakovich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .sorted(Comparator.comparingInt(film -> film.getLikes().size()));
Не поняла, о чем ты говоришь во втором предложении, не мог бы пояснить?

По ссылке, которую я дала выше, очень похожая ситуация обрабатывается - в зависимости от параметров фильтрация происходит по разным колонкам. Логика того, в какой именно форме будет выполнен запрос в главном методе, а дальше он выбирает куда переадресовать:
```java
public Stream<Film> getMostPopularFilms(Integer count, Long genreId, Year year) {
  Stream<Film> popularFilms;

  if (genreId == null) {
    if (year == null) popularFilms = getMostPopularFilmsDefault(count);
    else popularFilms = getMostPopularFilmsByYear(count, year);
  } else {
    if (year == null) popularFilms = getMostPopularFilmsByGenre(count, genreId);
    else popularFilms = getMostPopularFilmsByGenreAndYear(count, genreId, year);
  }

  return popularFilms;
}
```

2022-08-21 15:52 UTC, AlexOdnoshivkin commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        String filter = "HAVING f.NAME ILIKE " + "'%" + query + "%'";
Да, ошибка с WHERE была связана именно с этим. С кодом вида WHERE director_name ILIKE ? повторюсь, он не работает. Видимо внедрение переменных работает только для значений. Т.е. я пробую делать как на скрине (Having пока специально оставил). И выборка не проходит. Т.е. не найдено совпадений.
![image](https://user-images.githubusercontent.com/100222349/185799590-4108a6fd-9c7a-49bd-ac38-cb6676e36697.png)

2022-08-21 16:34 UTC, AlexOdnoshivkin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .sorted(Comparator.comparingInt(film -> film.getLikes().size()));
Вот что я имею в виду: в том случае, что ты привела, мы выбираем запрос исходя из условий. Получаем стрим фильмов и отдаём его. В моём случае поиска, я тоже выбираю запрос, да, но у меня могут быть и оба запроса одновременно, которые возращают стрим фильмов. И тут без объединения в этом случае никак. Сразу сортировать в этих запросах смысла нет, так как после объединения он снова будет не сортирован. И тут 2 пути, как я это вижу: либо сортировать уже имеющийся стрим фильмов, либо писать новый метод, который принимает например список id фильмов, делает запрос к бд и возвращает новый список с фильмами. Мне показалось, что второй вариант хуже. Писать прилично кода и мы получается будем 2 раза запрашивать одни и те же фильмы

2022-08-21 17:21 UTC, PolinaMalakovich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .sorted(Comparator.comparingInt(film -> film.getLikes().size()));
Думала, что чего-то не заметила, но попробовола сама, и всё работает.
```java
public Stream<Film> search(String query, String by) {
    boolean byDirector = by.contains("director");
    boolean byTitle = by.contains("title");
    Stream<Film> results;

    if (byDirector) {
        if (byTitle) results = searchFilmByNameOrDirector(query);
        else results = searchFilmByDirector(query);
    } else {
        if (byTitle) results = searchFilmByName(query);
        else results = Stream.empty();
    }

    return results;
}

private Stream<Film> searchFilmByName(String query) {
    String sqlQuery = "SELECT f.film_id, " +
        "       f.name, " +
        "       f.description, " +
        "       f.release_date, " +
        "       f.duration, " +
        "       f.mpa_id, " +
        "       m.name " +
        "FROM films AS f " +
        "LEFT JOIN mpa AS m ON m.mpa_id = f.mpa_id " +
        "LEFT JOIN likes AS l ON l.film_id = f.film_id " +
        "WHERE f.name ILIKE ? " +
        "GROUP BY f.film_id " +
        "ORDER BY COUNT(l.user_id) DESC;";
    return jdbcTemplate.query(sqlQuery, this::mapRowToFilm, "%" + query + "%")
        .stream();
}
private Stream<Film> searchFilmByDirector(String query) {
    String sqlQuery = "SELECT f.film_id, " +
        "       f.name, " +
        "       f.description, " +
        "       f.release_date, " +
        "       f.duration, " +
        "       f.mpa_id, " +
        "       m.name " +
        "FROM films AS f " +
        "LEFT JOIN mpa AS m ON m.mpa_id = f.mpa_id " +
        "LEFT JOIN films_directors AS fd ON f.film_id = fd.film_id " +
        "LEFT JOIN directors AS d ON fd.director_id = d.director_id " +
        "LEFT JOIN likes AS l ON l.film_id = f.film_id " +
        "WHERE d.director_name ILIKE ? " +
        "GROUP BY f.film_id " +
        "ORDER BY COUNT(l.user_id) DESC;";
    return jdbcTemplate.query(sqlQuery, this::mapRowToFilm, "%" + query + "%")
        .stream();
}
private Stream<Film> searchFilmByNameOrDirector(String query) {
    String sqlQuery = "SELECT f.film_id,  " +
        "       f.name,  " +
        "       f.description,  " +
        "       f.release_date,  " +
        "       f.duration,  " +
        "       f.mpa_id,  " +
        "       m.name  " +
        "FROM films AS f  " +
        "LEFT JOIN mpa AS m ON m.mpa_id = f.mpa_id  " +
        "LEFT JOIN films_directors AS fd ON f.film_id = fd.film_id  " +
        "LEFT JOIN directors AS d ON fd.director_id = d.director_id  " +
        "LEFT JOIN likes AS l ON l.film_id = f.film_id  " +
        "WHERE d.director_name ILIKE ? OR f.name ILIKE ?  " +
        "GROUP BY f.film_id  " +
        "ORDER BY COUNT(l.user_id) DESC;";
    return jdbcTemplate.query(sqlQuery, this::mapRowToFilm, "%" + query + "%", "%" + query + "%")
        .stream();
}
```

2022-08-22 07:45 UTC, jrDimagnit approved these changes

2022-08-22 09:33 UTC, PolinaMalakovich approved these changes

2022-08-22 15:37 UTC, merged