Film refactoring update
AlexOdnoshivkin/java-filmorate pull request #26
Opened 2022-08-23 22:16 UTC by AlexOdnoshivkin

1. Исправил таблицу с рейтингами. Рейтинг записываем как int, a не float, добавил составной ключ для уникальности значений.
2. К контроллере FilmController с учётом этого в методе putLike изменил float на int/
3.  Дополнил класс FilmRatingDbStorage: добавил обновление и получение рейтинга фильмов. В метод addRating добавил проверку на наличие оценки от пользователя. Возможно стоило в этом случае просто вызвать запрос на обновление рейтинга, а не кидать исключение и делать отдельный метод для обновления, но пока что предположил, что для обновления оценки от юзера будет свой http=метод PUT.
4. В классе FilmService обновил методы с учётом изменений выше. В методах, где возвращаются фильмы, добавил получение рейтинга фильма.

2022-08-24 08:40 UTC, PolinaMalakovich requested changes

2022-08-24 08:40 UTC, PolinaMalakovich commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmRatingDbStorage.java
> +        if (affected == 0) {
`affected == 0` показывает, что в таблице нет записи с таким `film_id` и `user_id`. Кроме того, в запросе выше пропущен `userId` в передаче параметров. 

Лучше делать обычный `INSERT` с обработкой ошибки, на случай если запись с таким `film_id` и `user_id` уже существует. Сейчас не могу проверить, скорее всего, будет `DuplicateKeyException`.

2022-08-24 08:40 UTC, PolinaMalakovich commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmRatingDbStorage.java
> +        jdbcTemplate.update(sqlQuery, id, userId);
Здесь, как и выше в `updateRating`, `jdbcTemplate.update` возвращает количество `affected` записей. `affected == 0` должно приводить к `404 Not Found`

2022-08-24 08:40 UTC, PolinaMalakovich commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmRatingDbStorage.java
> +    public void getFilmRating(Film film) {
Геттер работает как сеттер?

2022-08-24 08:40 UTC, PolinaMalakovich commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmRatingDbStorage.java
> +                "GROUP BY FILM_ID";
Если рейтинг сеттится отдельно, ломаются все сортировки. Чтобы работало как раньше и не пришлось делать сортировки на уровне java, нужно ту же логику, которая уже есть во всех `SELECT FILMS`, обновить для работы с рейтингами.

2022-08-24 09:44 UTC, AlexOdnoshivkin commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmRatingDbStorage.java
> +    public void getFilmRating(Film film) {
Забавно получилось, да) Изначально делал что метод возвращает Float, но потом решил устанавливать рейтинг прямо здесь, а название не поменял) Получилось get из таблицы и set в film)

2022-08-24 11:11 UTC, MaksimOrekhoff commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmRatingDbStorage.java
> +        if (affected == 0) {
лучше это прописать при обновлении. ведь при добавлении рейтинга впервые affected = 0. таких строк в БД еще нет и вылетает ошибка

2022-08-24 11:12 UTC, MaksimOrekhoff commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmRatingDbStorage.java
> +        if (affected == 0) {
либо заменить на affected  != 0

2022-08-24 20:38 UTC, AlexOdnoshivkin commented
1. Доработал выброс исключения при дублировании оценки, тепер при наличии оценки я просто вызываю метод update. Сделал так потому-что у нас видимо метод контроллера для рейтинга будет один - PUT, как это было сделано в лайках.
2. Метод CalculateFilmRating пока оставил. После объединения веток думаю его убрать, Максим сделал расчёт рейтинга в методах сортировки и т.д., поэтому думаю надо будет записть рейтинга внедрить напрямую в mapRowToFilm.
3. Доработал события под рейтинги

2022-08-25 13:35 UTC, PolinaMalakovich requested changes

2022-08-25 13:35 UTC, PolinaMalakovich commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
>      public void deleteLike(@PathVariable long id, @PathVariable long userId) {
Сейчас на этом методе висит две аннотации: `@PutMapping` и `@DeleteMapping`. `@PutMapping` видимо остался по ошибке, стоит удалить.

2022-08-25 13:35 UTC, PolinaMalakovich commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmRatingStorage.java
> +    void CalculateFilmRating(Film film);
Надо написать с маленькой буквы.

2022-08-25 13:35 UTC, PolinaMalakovich commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmRatingDbStorage.java
> +        } catch (DuplicateKeyException e) {
Нарушается принцип единственной ответственности (single responsibility principle). `add` должен только добавлять, `update` только обновлять. Каждый из них должен хорошо выполнять свою задачу: `add` должен сообщать о нестандартной для него ситуации ("Такая запись уже есть"), как и `update` ("Такой записи нет"). Метод, который ты написал, это не `add`, а `save` (или `upsert`). Он должен реализовываться на логике отдельных методов `add` и `update` . Кроме того, при текущей реализации `DuplicateKeyException` никогда не покидает пределы этого метода, а значит `ErrorHandler` никогда не используется. Пердлагаю такую реализацию:

```java
public void addRating(long id, long userId, int rating) {
  String sqlQuery = "INSERT INTO film_ratings (film_id, user_id, user_rating) VALUES (?, ?, ?)";
  jdbcTemplate.update(sqlQuery, id, userId, rating); // упадёт с DuplicateKeyException, обработается в ErrorHandler
  log.debug("Добавлен рейтинг {} фильму с id {} пользователем с id {}", rating, id, userId);
}

public void updateRating(long id, long userId, int rating) {
  String sqlQuery = "UPDATE film_ratings set user_rating = ? where film_id = ? AND user_id = ?";
  int affected = jdbcTemplate.update(sqlQuery, id, userId, rating);
  if (affected == 0) throw new EntityNotFoundException("Запись не найдена");
  log.debug("Обновлён рейтинг фильма с id {} пользователем с id {}, новый рейтинг: {}", id, userId, rating);
}

public void saveRating(long id, long userId, int rating) {
  String sqlQuery = "SELECT * FROM film_ratings WHERE film_id = ? AND user_id = ?";
  Map<String, Object> ratingFields = jdbcTemplate.queryForMap(sqlQuery, id, userId);
  if (ratingFields.isEmpty()) addRating(id, userId, rating);
  else updateRating(id, userId, rating);
}
```

2022-08-25 21:51 UTC, AlexOdnoshivkin commented
1. Сделал мёрж ветки Максима
2.  Доработал FilmRatingDbStorage
3. Сделал установку рейтинга прямо в маппинге фильмов
4. Поправил вывод общих фильмов: теперь выводятся общие фильмы с положительным рейтингом
5. Немного подправил тесты в связи с этим

2022-08-26 11:14 UTC, PolinaMalakovich approved these changes

2022-08-26 12:59 UTC, MaksimOrekhoff approved these changes

2022-08-26 13:38 UTC, merged