Add friends likes
AlexOdnoshivkin/java-filmorate pull request #4
Opened 2022-07-14 20:49 UTC by AlexOdnoshivkin

2022-07-15 16:30 UTC, kukolev requested changes

2022-07-15 16:30 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        /*return user.getFriends().stream()
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-07-15 16:30 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +@Component(value = "a")
Если value здесь действительно нужен, то лучше сделать более понятное значение.

2022-07-15 19:21 UTC, AlexOdnoshivkin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        /*return user.getFriends().stream()
Спасибо, исправил

2022-07-15 19:21 UTC, AlexOdnoshivkin commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +@Component(value = "a")
Исправил, удалил value, он тут не нужен

2022-07-16 08:48 UTC, kukolev requested changes

2022-07-16 08:48 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +@Scope("singleton")
Скоуп синглтон не нужно прописывать, т.к. это скоуп по умолчанию для всех бинов спринга. Этот код лишний и его нужно удалить.

2022-07-16 08:57 UTC, AlexOdnoshivkin commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +@Scope("singleton")
Спасибо, удалил из всех классов

2022-07-18 07:12 UTC, kukolev approved these changes

2022-07-21 18:52 UTC, merged