Add database
AlexOdnoshivkin/java-filmorate pull request #9
Opened 2022-08-11 14:55 UTC by AlexOdnoshivkin

2022-08-12 07:23 UTC, kukolev requested changes

2022-08-12 07:23 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +	public static void main(String[] args) {
Отступы перед кодом выполнены с помощью Tab. Необходимо привести в соответствии с кодстайлом и сделать отступы пробелами.

2022-08-12 07:23 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/model/users/User.java
> +    //private final Map<Long, FriendStatus> friends = new HashMap<>();
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-08-12 07:23 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/model/users/User.java
> +    /*public void addToFriend(long id) {
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-08-12 07:23 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        //Film film = storage.getById(id);
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-08-12 07:23 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        String sqlQuery = "INSERT INTO FILMS (NAME, DESCRIPTION, RELEASE_DATE, DURATION, MPA_ID) VALUES (?, ?, ?, ?, ?) ";
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-12 07:23 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FriendDbStorage.java
> +        log.debug("Выгружен список общих друзей для пользователей с id {} и {}, количестов друзей: {}", id, otherId, users.size());
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-12 07:23 UTC, kukolev commented on src/main/resources/application.properties
> +#spring.datasource.url=jdbc:h2:mem:filmorate
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-08-12 15:01 UTC, AlexOdnoshivkin commented
Внёс исправления по замечаниям ревью 1

2022-08-12 21:41 UTC, kukolev requested changes

2022-08-12 21:41 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreStorage.java
> +    public List<Genre> getAllGenres();
В интерфейсах нет необходимости писать public перед методами, т.к. все методы интерфейса всегда публичные. Именно по этому IDEA выделяет слово public серым цветом.

2022-08-12 21:41 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/MpaStorage.java
> +    public List<Mpa> getAllMpa();
В интерфейсах нет необходимости писать public перед методами, т.к. все методы интерфейса всегда публичные. Именно по этому IDEA выделяет слово public серым цветом.

2022-08-12 21:41 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        String sqlQuery = "SELECT\n" +
Здесь и в подобных запросах символ переноса каретки \n лишний. Его можно удалить, код станет проще и функционал от этого не пострадает.

2022-08-13 03:16 UTC, AlexOdnoshivkin commented
Внёс исправления по замечаниям ревью 2

2022-08-14 06:57 UTC, kukolev approved these changes

2022-08-14 12:12 UTC, merged